services:
  - type: web
    name: investing-news-api
    env: python
    plan: free # Hoặc chọn gói trả phí nếu cần
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4 # Chỉ định phiên bản Python bạn muốn sử dụng
